### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by zaynyatyi** [HaxeExtension/extension-webview#8]
Hi,
i have exception on android when trying to open url
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gomadkids.turmali/extensions.webview.WebViewActivity}: java.lang.NullPointerException

unfortunately i can't build extension with -debug flag to provide more information.
Tried different url's (on iOs working perfectly)

**Comment by zaynyatyi** [comment]
E/AndroidRuntime(21883): Caused by: java.lang.NullPointerException
E/AndroidRuntime(21883):    at extensions.webview.WebViewActivity.initUI(WebViewActivity.java:163)
E/AndroidRuntime(21883):    at extensions.webview.WebViewActivity.onCreate(WebViewActivity.java:53)
E/AndroidRuntime(21883):    at android.app.Activity.performCreate(Activity.java:5277)
E/AndroidRuntime(21883):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
E/AndroidRuntime(21883):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)

That's what i got from debug view.
callback.call("onURLChanging", new Object[] {url}); crashes here, but onUrlChanging callback assigned in haxe app.

**Comment by fbricker** [comment]
Hi people, is this situation still happening?
Are you testing with openfl next or legacy?
